"""Ingest synthetic demo data for Brazos County, TX.

This script creates **clearly-labeled synthetic** demo data — it is NOT real
wetland, floodplain, or transmission line data. It exists to exercise the
full analysis pipeline end-to-end without requiring access to authoritative
datasets.

Usage:
    python -m scripts.ingest_demo_data
    # or
    python scripts/ingest_demo_data.py

Requires a PostGIS-enabled PostgreSQL database configured via DATABASE_URL.
"""

from __future__ import annotations

import sys
import uuid
from datetime import UTC, datetime
from pathlib import Path

# Allow running as ``python scripts/ingest_demo_data.py`` from the backend dir
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from shapely.geometry import Point, Polygon
from sqlalchemy import create_engine, text
from sqlalchemy.orm import Session

from app.core.config import get_settings
from app.db.base import Base
from app.db.models.dataset_metadata import DatasetMetadata
from app.db.models.parcel import Parcel
from app.geometry.ops import area_sqm, sqm_to_acres

# Bryan / College Station, TX area (approximate center)
BRYAN_CS_LON = -96.33
BRYAN_CS_LAT = 30.63

DEMO_NOTE = (
    "SYNTHETIC DEMO DATA — NOT REAL. This record was generated by "
    "scripts/ingest_demo_data.py for development and testing purposes only. "
    "It does not represent authoritative wetland, floodplain, or transmission "
    "line information."
)


def make_parcel_polygon(
    center_lon: float,
    center_lat: float,
    width_meters: float,
    height_meters: float,
    rotation_deg: float = 0.0,
) -> Polygon:
    """Create a rectangular parcel polygon centered at the given WGS84 point.

    Width/height are in metres in the analysis CRS; the polygon is generated
    in the analysis CRS and then converted to WGS84 for display.
    """
    import math

    from shapely.geometry import box as shapely_box
    from shapely.ops import transform

    from app.geometry.crs import get_transformer

    settings = get_settings()
    # Transform center from WGS84 to analysis CRS
    transformer = get_transformer(settings.WGS84_CRS, settings.ANALYSIS_CRS)
    cx, cy = transformer.transform(center_lon, center_lat)

    half_w = width_meters / 2
    half_h = height_meters / 2
    rect = shapely_box(cx - half_w, cy - half_h, cx + half_w, cy + half_h)

    if rotation_deg:
        angle = math.radians(rotation_deg)
        cos_a = math.cos(angle)
        sin_a = math.sin(angle)

        def rotate(x, y):
            dx = x - cx
            dy = y - cy
            return (cx + dx * cos_a - dy * sin_a, cy + dx * sin_a + dy * cos_a)

        rect = transform(rotate, rect)

    return rect


def make_constraint_polygon(
    center_lon: float,
    center_lat: float,
    width_meters: float,
    height_meters: float,
) -> Polygon:
    """Create a rectangular constraint polygon in the analysis CRS."""
    settings = get_settings()
    from shapely.geometry import box as shapely_box

    from app.geometry.crs import get_transformer

    transformer = get_transformer(settings.WGS84_CRS, settings.ANALYSIS_CRS)
    cx, cy = transformer.transform(center_lon, center_lat)

    half_w = width_meters / 2
    half_h = height_meters / 2
    return shapely_box(cx - half_w, cy - half_h, cx + half_w, cy + half_h)


def to_wkt_with_srid(geom, srid: int) -> str:
    """Return a WKT string with SRID prefix for ST_GeomFromEWKT."""
    return f"SRID={srid};{geom.wkt}"


def ingest_parcels(session: Session) -> list[Parcel]:
    """Create 5 synthetic demo parcels around Bryan/College Station, TX."""
    parcels_data = [
        # (display_name, source_id, lon_offset, lat_offset, width_m, height_m, rotation, address)
        (
            "Demo Parcel A - Brazos County",
            "DEMO-PARCEL-A",
            -0.005,
            0.003,
            450,
            450,
            0,
            "Demo Area A, Brazos County, TX",
        ),
        (
            "Demo Parcel B - Near Navasota River",
            "DEMO-PARCEL-B",
            0.010,
            -0.004,
            700,
            740,
            15,
            "Demo Area B, Brazos County, TX",
        ),
        (
            "Demo Parcel C - College Station Area",
            "DEMO-PARCEL-C",
            -0.002,
            -0.006,
            240,
            250,
            0,
            "Demo Area C, College Station, TX",
        ),
        (
            "Demo Parcel D - South Brazos",
            "DEMO-PARCEL-D",
            0.006,
            0.008,
            350,
            350,
            30,
            "Demo Area D, Brazos County, TX",
        ),
        (
            "Demo Parcel E - West of Bryan",
            "DEMO-PARCEL-E",
            -0.012,
            0.001,
            300,
            300,
            0,
            "Demo Area E, Bryan, TX",
        ),
    ]

    created: list[Parcel] = []
    for display_name, source_id, lon_off, lat_off, w, h, rot, address in parcels_data:
        lon = BRYAN_CS_LON + lon_off
        lat = BRYAN_CS_LAT + lat_off

        analysis_geom = make_parcel_polygon(lon, lat, w, h, rot)
        wgs84_geom = _to_wgs84(analysis_geom)
        centroid_wgs84 = Point(wgs84_geom.centroid.x, wgs84_geom.centroid.y)

        area_acres = sqm_to_acres(area_sqm(analysis_geom))

        parcel = Parcel(
            id=uuid.uuid4(),
            source_id=source_id,
            county_name="Brazos",
            display_name=display_name,
            address=address,
            source_area_acres=round(area_acres, 4),
            properties={
                "synthetic": True,
                "demo": True,
                "note": DEMO_NOTE,
            },
        )
        # Use raw SQL for geometry insertion to ensure proper SRID
        session.execute(
            text("""
                INSERT INTO parcels
                    (id, source_id, county_name, display_name, address,
                     source_area_acres, geometry, geometry_wgs84, centroid_wgs84,
                     properties, created_at, updated_at)
                VALUES
                    (:id, :source_id, :county_name, :display_name, :address,
                     :source_area_acres,
                     ST_GeomFromEWKT(:geom),
                     ST_GeomFromEWKT(:geom_wgs84),
                     ST_GeomFromEWKT(:centroid),
                     :properties, now(), now())
            """),
            {
                "id": str(parcel.id),
                "source_id": parcel.source_id,
                "county_name": parcel.county_name,
                "display_name": parcel.display_name,
                "address": parcel.address,
                "source_area_acres": float(area_acres),
                "geom": to_wkt_with_srid(analysis_geom, 32614),
                "geom_wgs84": to_wkt_with_srid(wgs84_geom, 4326),
                "centroid": to_wkt_with_srid(centroid_wgs84, 4326),
                "properties": '{"synthetic": true, "demo": true, "note": "%s"}' % DEMO_NOTE,  # noqa: UP031
            },
        )
        created.append(parcel)
        print(f"  Created parcel: {display_name} ({area_acres:.2f} acres)")

    return created


def _to_wgs84(geom):
    from app.geometry.crs import to_wgs84

    return to_wgs84(geom)


def ingest_datasets(session: Session) -> dict[str, DatasetMetadata]:
    """Create dataset metadata records for the three synthetic constraint layers."""
    datasets = {}

    wetlands_ds = DatasetMetadata(
        id=uuid.uuid4(),
        name="Synthetic Demo Wetlands",
        provider="LandScope Demo (SYNTHETIC)",
        source_url="https://example.com/synthetic/wetlands",
        licence="Synthetic demo data — no licence, not for real use",
        retrieved_at=datetime.now(UTC),
        source_version="demo-1.0",
        analysis_crs="EPSG:32614",
        notes=DEMO_NOTE,
    )

    floodplain_ds = DatasetMetadata(
        id=uuid.uuid4(),
        name="Synthetic Demo FEMA Flood Hazard",
        provider="LandScope Demo (SYNTHETIC)",
        source_url="https://example.com/synthetic/floodplain",
        licence="Synthetic demo data — no licence, not for real use",
        retrieved_at=datetime.now(UTC),
        source_version="demo-1.0",
        analysis_crs="EPSG:32614",
        notes=DEMO_NOTE,
    )

    transmission_ds = DatasetMetadata(
        id=uuid.uuid4(),
        name="Synthetic Demo Transmission Lines",
        provider="LandScope Demo (SYNTHETIC)",
        source_url="https://example.com/synthetic/transmission",
        licence="Synthetic demo data — no licence, not for real use",
        retrieved_at=datetime.now(UTC),
        source_version="demo-1.0",
        analysis_crs="EPSG:32614",
        notes=DEMO_NOTE,
    )

    for ds in [wetlands_ds, floodplain_ds, transmission_ds]:
        session.execute(
            text("""
                INSERT INTO dataset_metadata
                    (id, name, provider, source_url, licence, retrieved_at,
                     source_version, analysis_crs, feature_count, notes, created_at)
                VALUES
                    (:id, :name, :provider, :source_url, :licence, :retrieved_at,
                     :source_version, :analysis_crs, :feature_count, :notes, now())
            """),
            {
                "id": str(ds.id),
                "name": ds.name,
                "provider": ds.provider,
                "source_url": ds.source_url,
                "licence": ds.licence,
                "retrieved_at": ds.retrieved_at,
                "source_version": ds.source_version,
                "analysis_crs": ds.analysis_crs,
                "feature_count": ds.feature_count,
                "notes": ds.notes,
            },
        )

    datasets["wetlands"] = wetlands_ds
    datasets["floodplain"] = floodplain_ds
    datasets["transmission"] = transmission_ds

    print(f"  Created dataset: {wetlands_ds.name}")
    print(f"  Created dataset: {floodplain_ds.name}")
    print(f"  Created dataset: {transmission_ds.name}")

    return datasets


def ingest_constraints(session: Session, datasets: dict[str, DatasetMetadata]) -> None:
    """Create synthetic constraint features overlapping some parcels."""

    # Wetlands: 4 polygons, some overlapping parcels A, B, D
    wetlands = [
        # (lon_off, lat_off, width_m, height_m, classification)
        (-0.004, 0.004, 120, 100, None),  # near Parcel A
        (0.011, -0.003, 200, 150, None),  # near Parcel B
        (0.007, 0.009, 80, 80, None),  # near Parcel D
        (-0.003, -0.005, 60, 60, None),  # near Parcel C
    ]

    for i, (lon_off, lat_off, w, h, cls) in enumerate(wetlands):
        geom = make_constraint_polygon(BRYAN_CS_LON + lon_off, BRYAN_CS_LAT + lat_off, w, h)
        session.execute(
            text("""
                INSERT INTO constraint_features
                    (id, dataset_id, layer_type, source_id, classification,
                     geometry, properties, created_at)
                VALUES
                    (:id, :dataset_id, 'wetlands', :source_id, :classification,
                     ST_GeomFromEWKT(:geom), :properties, now())
            """),
            {
                "id": str(uuid.uuid4()),
                "dataset_id": str(datasets["wetlands"].id),
                "source_id": f"DEMO-WETLAND-{i + 1}",
                "classification": cls,
                "geom": to_wkt_with_srid(geom, 32614),
                "properties": '{"synthetic": true, "demo": true}',
            },
        )
    print(f"  Created {len(wetlands)} wetland features")

    # Floodplain: 3 polygons with FEMA-style classifications
    floodplains = [
        # (lon_off, lat_off, width_m, height_m, classification)
        (0.010, -0.004, 500, 400, "AE"),  # near Parcel B
        (0.006, 0.008, 300, 200, "A"),  # near Parcel D
        (-0.011, 0.002, 250, 180, "X"),  # near Parcel E
    ]

    for i, (lon_off, lat_off, w, h, cls) in enumerate(floodplains):
        geom = make_constraint_polygon(BRYAN_CS_LON + lon_off, BRYAN_CS_LAT + lat_off, w, h)
        session.execute(
            text("""
                INSERT INTO constraint_features
                    (id, dataset_id, layer_type, source_id, classification,
                     geometry, properties, created_at)
                VALUES
                    (:id, :dataset_id, 'floodplain', :source_id, :classification,
                     ST_GeomFromEWKT(:geom), :properties, now())
            """),
            {
                "id": str(uuid.uuid4()),
                "dataset_id": str(datasets["floodplain"].id),
                "source_id": f"DEMO-FLOOD-{i + 1}",
                "classification": cls,
                "geom": to_wkt_with_srid(geom, 32614),
                "properties": '{"synthetic": true, "demo": true}',
            },
        )
    print(f"  Created {len(floodplains)} floodplain features")

    # Transmission: 2 already-buffered corridor polygons
    transmissions = [
        # (lon_off, lat_off, width_m, height_m) — these represent already-buffered corridors
        (-0.008, 0.000, 60, 800),  # vertical corridor near Parcel E
        (0.003, 0.005, 600, 50),  # horizontal corridor near Parcel A/D
    ]

    for i, (lon_off, lat_off, w, h) in enumerate(transmissions):
        geom = make_constraint_polygon(BRYAN_CS_LON + lon_off, BRYAN_CS_LAT + lat_off, w, h)
        session.execute(
            text("""
                INSERT INTO constraint_features
                    (id, dataset_id, layer_type, source_id, classification,
                     geometry, properties, created_at)
                VALUES
                    (:id, :dataset_id, 'transmission', :source_id, NULL,
                     ST_GeomFromEWKT(:geom), :properties, now())
            """),
            {
                "id": str(uuid.uuid4()),
                "dataset_id": str(datasets["transmission"].id),
                "source_id": f"DEMO-TRANS-{i + 1}",
                "geom": to_wkt_with_srid(geom, 32614),
                "properties": '{"synthetic": true, "demo": true, "pre_buffered": true}',
            },
        )
    print(f"  Created {len(transmissions)} transmission features")


def main() -> None:
    settings = get_settings()
    print(f"Connecting to database: {settings.DATABASE_URL}")
    engine = create_engine(settings.DATABASE_URL, pool_pre_ping=True, future=True)

    # Create tables if they don't exist (idempotent for demo purposes)
    print("Creating tables if needed...")
    Base.metadata.create_all(engine)

    with Session(engine) as session:
        # Clear existing demo data (idempotent re-run)
        print("Clearing existing demo data...")
        session.execute(text("DELETE FROM constraint_features"))
        session.execute(text("DELETE FROM dataset_metadata"))
        session.execute(text("DELETE FROM parcels"))
        session.commit()

        print("Ingesting synthetic parcels...")
        ingest_parcels(session)
        session.commit()

        print("Ingesting dataset metadata...")
        datasets = ingest_datasets(session)
        session.commit()

        print("Ingesting constraint features...")
        ingest_constraints(session, datasets)
        session.commit()

    print("\nDemo data ingestion complete!")
    print("All data is SYNTHETIC and clearly labeled as demo.")


if __name__ == "__main__":
    main()
